apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:Romanecek/kb-poc-argo-central.git
        revision: tenants
        directories:
          - path: '*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: git@github.com:Romanecek/kb-poc-argocd-argocd-app.git
        targetRevision: main
        path: '.'
        helm:
          valueFiles:
            - $values/{{.path.basename}}/values.yaml
      - repoURL: git@github.com:Romanecek/kb-poc-argo-central.git
        targetRevision: tenants
        path: '{{.path.basename}}'
        ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true